### ISSUE TITLE
@typescript-eslint/experimental-utils dependency

### ISSUE THREAD

**Issue by stropho** [fa93hws/eslint-snapshot-test#64]
Hi, thanks for the tool. Can be very useful in some cases.
I somehow made it work, but had some issues.

1. `@typescript-eslint/experimental-utils` is defined as devDependecy but is used in runtime :(
2. `@typescript-eslint/experimental-utils` has been deprecated. The folder structure of `@typescript-eslint/experimental-utils/dist` is slightly different in the latest version.
 - https://www.npmjs.com/package/@typescript-eslint/experimental-utils
 - https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/utils/CHANGELOG.md#5100-2022-01-17

My suggestion:
1. update the `@typescript-eslint/*` packages
2. use `@typescript-eslint/utils` instead `@typescript-eslint/experimental-utils`, do not import from `dist/`
3. make `@typescript-eslint/utils` dependency or peerDependecy . I'd vote for peerDeps so users can update `@typescript-eslint/utils` to whatever version they want.

I can do the PR if you want. Just let me know... 😸

**Comment by fa93hws** [comment]
Are you happy with https://github.com/fa93hws/eslint-snapshot-test/pull/65?
